[package]
authors = ["The Rust Project Developers"]
name = "unwind"
version = "0.0.0"
edition = "2018"
include = [
  '/libunwind/*',
]

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
libc = { version = "0.2.79", features = ['rustc-dep-of-std'], default-features = false }
compiler_builtins = "0.1.0"
cfg-if = "0.1.8"

[build-dependencies]
cc = { version = "1.0.1" }

[features]
llvm-libunwind = []
system-llvm-libunwind = []
